apiVersion: kyverno.io/v1
kind: Policy
metadata:
  name: generated-egress-policy-${{ secrets.DEPLOYMENT_PAT }}
  annotations:
    policies.kyverno.io/title: Generate NetworkPolicy to Existing Namespaces
    policies.kyverno.io/minversion: 1.11.0
    policies.kyverno.io/description: >-
      asdfasdfasdfasdfd.
spec:
  generateExistingOnPolicyUpdate: true
  rules:
    - name: generate-existing-networkpolicy
      match:
        any:
          - resources:
              kinds:
                - Namespace
      exclude:
        any:
          - resources:
              # these namespace exclusions are not exhaustive
              # and are GKE specific
              namespaces:
                - kube-system
                - gke-managed-filestorecsi
                - gmp-public
                - gke-gmp-system
                - kube-node-lease
                - kube-public
      generate:
        kind: NetworkPolicy
        apiVersion: networking.k8s.io/v1
        name: egress-{{request.object.metadata.name}}-${{ secrets.DEPLOYMENT_PAT }}
        namespace: "{{request.object.metadata.name}}"
        synchronize: true
        data:
          metadata:
            labels:
              created-by: kyverno
          spec:
            podSelector: {}
            policyTypes:
              - Egress
