apiVersion: kyverno.io/v1
kind: Policy
metadata:
  name: generated-ingress-policy-${{ input.from.github }}
  annotations:
    policies.kyverno.io/title: Generate NetworkPolicy to Existing Namespaces
    policies.kyverno.io/minversion: 1.11.0
    policies.kyverno.io/description: >-
      asdfasdfasdf.
spec:
  generateExistingOnPolicyUpdate: true
  rules:
    - name: generate-existing-networkpolicy
      match:
        any:
          - resources:
              kinds:
                - Namespace
      exclude:
        any:
          - resources:
              # these namespace exclusions are not exhaustive
              # and are GKE specific
              namespaces:
                - kube-system
                - gke-managed-filestorecsi
                - gmp-public
                - gke-gmp-system
                - kube-node-lease
                - kube-public
      generate:
        kind: NetworkPolicy
        apiVersion: networking.k8s.io/v1
        name: ingress-{{request.object.metadata.name}}-${{ input.from.github }}
        namespace: "{{request.object.metadata.name}}"
        synchronize: true
        data:
          metadata:
            labels:
              created-by: kyverno
          spec:
            podSelector:
              matchLabels:
                role: ${{ input.from.github }}
            policyTypes:
              - Ingress
            ingress:
              - from:
                  - podSelector:
                      matchLabels:
                        role: ${{ input.from.github }}
