apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: generate-default-deny-networkpolicy-existing
  annotations:
    policies.kyverno.io/title: Generate NetworkPolicy to Existing Namespaces
    policies.kyverno.io/minversion: 1.11.0
    policies.kyverno.io/description: >-
      A NetworkPolicy enforcing default-deny on traffic, except for things which are explicitly labeled
      for egress or ingress traffic. By default the policy enforces this to the local namespace scope.
spec:
  generateExistingOnPolicyUpdate: true
  rules:
    - name: generate-existing-networkpolicy
      match:
        any:
          - resources:
              kinds:
                - Namespace
      exclude:
        any:
          - resources:
              # these namespace exclusions are not exhaustive
              # and are GKE specific
              namespaces:
                - kube-system
                - gke-managed-filestorecsi
                - gmp-public
                - gke-gmp-system
                - kube-node-lease
                - kube-public
      generate:
        kind: NetworkPolicy
        apiVersion: networking.k8s.io/v1
        name: default-deny
        namespace: "{{request.object.metadata.name}}"
        synchronize: true
        data:
          metadata:
            labels:
              created-by: kyverno
          spec:
            podSelector: {}
            policyTypes:
              - Ingress
              - Egress
            egress:
              - from:
                  - podSelector:
                      matchLabels:
                        egressAccess: "true"
            ingress:
              - from:
                  - podSelector:
                      matchLabels:
                        ingressAccess: "true"
